### 200 
POST http://localhost:5000/api/phones
Content-Type: application/json

{
    "brand": "Samsung",
    "model": "Galaxy Ultra",
    "manufacturedYear": "2025-10-12",
    "ram": "12",
    "cpu": "6",
    "screenSize": "6.6",
    "isNfc": true
}

### 200
GET http://localhost:5000/api/phones

### 200
GET http://localhost:5000/api/phones?page=2&results=3